# Generated by Django 2.0.2 on 2018-04-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nfl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('play', models.CharField(max_length=100)),
            ],
        ),
    ]
