# Generated by Django 2.0.2 on 2018-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nesports', '0002_nfl'),
    ]

    operations = [
        migrations.CreateModel(
            name='NflData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('team', models.CharField(max_length=10)),
                ('player', models.CharField(max_length=50)),
                ('passyards', models.IntegerField()),
                ('rushyards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('two_pt', models.IntegerField()),
            ],
        ),
    ]
